export const ADD_RESERVATION = 'ADD_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const NEXT_COVER = 'NEXT_COVER';

export const SET_RESERVATION_VISIBILITY = 'UPDATE_RESERVATION_VISIBILITY';
export const ALL_RESERVATIONS_VISIBLE = 'ALL_RESERVATIONS_VISIBLE';
export const MY_RESERVATIONS_VISIBLE = 'MY_RESERVATIONS_VISIBLE';
