export const ADD_RESERVATION = 'ADD_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const NEXT_COVER = 'NEXT_COVER';
